# Generated by Django 4.2.26 on 2025-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], max_length=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('tax_preference', models.CharField(blank=True, max_length=20)),
                ('hsn_or_sac', models.CharField(blank=True, max_length=20)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='zoho_items/')),
                ('is_sellable', models.BooleanField(default=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account_name', models.CharField(blank=True, max_length=50)),
                ('sales_description', models.TextField(blank=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_account_name', models.CharField(blank=True, max_length=50)),
                ('preferred_vendor', models.CharField(blank=True, max_length=100)),
                ('purchase_description', models.TextField(blank=True)),
                ('zoho_item_id', models.CharField(blank=True, max_length=50)),
                ('zoho_raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
