# Generated by Django 4.2.26 on 2025-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('PIECE', 'PIECE'), ('BOX', 'BOX'), ('SET', 'SET'), ('UNIT', 'UNIT')], default='PIECE', max_length=20)),
                ('tax_preference', models.CharField(choices=[('taxable', 'Taxable'), ('non_taxable', 'Non-Taxable')], default='taxable', max_length=20)),
                ('hsn_or_sac', models.CharField(blank=True, default='', max_length=30)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='zoho_items/')),
                ('is_sellable', models.BooleanField(default=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_account', models.CharField(blank=True, choices=[('sales', 'Sales'), ('service_income', 'Service Income'), ('cogs', 'Cost of Goods Sold'), ('other_income', 'Other Income')], default='sales', max_length=50)),
                ('sales_description', models.TextField(blank=True, default='')),
                ('is_purchasable', models.BooleanField(default=False)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_account', models.CharField(blank=True, choices=[('sales', 'Sales'), ('service_income', 'Service Income'), ('cogs', 'Cost of Goods Sold'), ('other_income', 'Other Income')], default='cogs', max_length=50)),
                ('preferred_vendor', models.CharField(blank=True, choices=[('', 'None'), ('vendor_a_id', 'Vendor A (Mobile Wholesaler)'), ('vendor_b_id', 'Vendor B (Component Supplier)')], default='', max_length=50)),
                ('purchase_description', models.TextField(blank=True, default='')),
                ('zoho_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_status', models.CharField(default='PENDING', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ZohoItem',
        ),
    ]
