# Generated by Django 4.2.26 on 2025-12-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0002_localitem_delete_zohoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique Stock Keeping Unit', max_length=100, null=True, unique=True),
        ),
    ]
