# Generated by Django 4.2.26 on 2025-12-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0003_localitem_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localitem',
            name='last_error',
        ),
    ]
