# Generated by Django 4.2.26 on 2025-12-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0004_remove_localitem_last_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('zoho_contact_id', models.CharField(blank=True, default='', help_text='Zoho Books contact_id', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent')], default='DRAFT', max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('gst_treatment', models.CharField(choices=[('no_tax_0', 'No Tax (0%)'), ('gst_5', 'GST 5%'), ('gst_12', 'GST 12%'), ('gst_18', 'GST 18%'), ('gst_28', 'GST 28%')], default='no_tax_0', max_length=30)),
                ('sync_status', models.CharField(default='PENDING', max_length=20)),
                ('zoho_invoice_id', models.CharField(blank=True, default='', max_length=80)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='zoho_integration.localcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='LocalInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='zoho_integration.localinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zoho_integration.localitem')),
            ],
        ),
    ]
