# Generated by Django 4.2.26 on 2025-12-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0005_localcustomer_localinvoice_localinvoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcustomer',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='localcustomer',
            name='sync_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
