# Generated by Django 4.2.26 on 2025-12-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0006_localcustomer_last_error_localcustomer_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcustomer',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
