# Generated by Django 4.2.26 on 2025-12-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0007_localcustomer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localinvoice',
            name='gst_treatment',
        ),
        migrations.RemoveField(
            model_name='localinvoice',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='localinvoice',
            name='sync_status',
        ),
        migrations.RemoveField(
            model_name='localinvoice',
            name='zoho_invoice_id',
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='apply_gst_to_all_items',
            field=models.CharField(choices=[('NO_TAX', 'No Tax (0%)'), ('GST_5', '5% GST (2.5% CGST + 2.5% SGST)'), ('GST_12', '12% GST (6% CGST + 6% SGST)'), ('GST_18', '18% GST (9% CGST + 9% SGST)'), ('GST_28', '28% GST (14% CGST + 14% SGST)'), ('IGST_5', '5% IGST'), ('IGST_12', '12% IGST'), ('IGST_18', '18% IGST'), ('IGST_28', '28% IGST')], default='NO_TAX', max_length=20),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='gst_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='gst_treatment',
            field=models.CharField(choices=[('NO_TAX', 'No Tax (0%)'), ('GST_5', '5% GST (2.5% CGST + 2.5% SGST)'), ('GST_12', '12% GST (6% CGST + 6% SGST)'), ('GST_18', '18% GST (9% CGST + 9% SGST)'), ('GST_28', '28% GST (14% CGST + 14% SGST)'), ('IGST_5', '5% IGST'), ('IGST_12', '12% IGST'), ('IGST_18', '18% IGST'), ('IGST_28', '28% IGST')], default='NO_TAX', max_length=20),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='line_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='localinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zoho_integration.localcustomer'),
        ),
        migrations.AlterField(
            model_name='localinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='localinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid')], default='DRAFT', max_length=20),
        ),
    ]
