# Generated by Django 4.2.26 on 2025-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0008_remove_localinvoice_gst_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinvoice',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='sync_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='localinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, unique=True),
        ),
    ]
