# Generated by Django 4.2.26 on 2025-12-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0009_localinvoice_last_error_localinvoice_sync_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localinvoice',
            name='sync_status',
            field=models.CharField(blank=True, default='PENDING', max_length=20),
        ),
    ]
