# Generated by Django 4.2.26 on 2025-12-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0011_localinvoice_zoho_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localinvoice',
            name='zoho_invoice_id',
        ),
    ]
