# Generated by Django 4.2.26 on 2025-12-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0012_remove_localinvoice_zoho_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinvoice',
            name='zoho_invoice_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Zoho Books invoice_id', max_length=80),
        ),
    ]
