# Generated by Django 4.2.26 on 2025-12-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0013_localinvoice_zoho_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
