# Generated by Django 4.2.26 on 2025-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0014_alter_localinvoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitem',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
