# Generated by Django 4.2.26 on 2025-12-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0015_localitem_service_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localinvoice',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='discount_type',
            field=models.CharField(choices=[('AMOUNT', 'Rupees (₹)'), ('PERCENT', 'Percentage (%)')], default='PERCENT', max_length=10),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='If type=PERCENT → %, if type=AMOUNT → ₹', max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='service_charge_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='line_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='service_charge_type',
            field=models.CharField(choices=[('AMOUNT', 'Rupees (₹)'), ('PERCENT', 'Percentage (%)')], default='AMOUNT', max_length=10),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='service_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='localinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Computed final discount in ₹', max_digits=12),
        ),
    ]
