# Generated by Django 4.2.26 on 2025-12-22 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoho_integration', '0016_remove_localinvoice_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcustomer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localcustomer',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localitem',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
