# Generated by Django 4.2.26 on 2025-12-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0017_localcustomer_created_by_localcustomer_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitem',
            name='gst_treatment',
            field=models.CharField(blank=True, choices=[('NO_TAX', 'No Tax (0%)'), ('IGST_5', '5% IGST'), ('IGST_12', '12% IGST'), ('IGST_18', '18% IGST'), ('IGST_28', '28% IGST'), ('GST_5', '5% GST (2.5% CGST + 2.5% SGST)'), ('GST_12', '12% GST (6% CGST + 6% SGST)'), ('GST_18', '18% GST (9% CGST + 9% SGST)'), ('GST_28', '28% GST (14% CGST + 14% SGST)')], default='NO_TAX', max_length=20),
        ),
    ]
