# Generated by Django 4.2.26 on 2025-12-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0018_localitem_gst_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinvoice',
            name='terms_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
