# Generated by Django 4.2.26 on 2026-01-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_lead'),
        ('zoho_integration', '0019_localinvoice_terms_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinvoice',
            name='assigned_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_invoices', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_invoices', to='core.shop'),
        ),
        migrations.AlterField(
            model_name='localinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
