# Generated by Django 4.2.26 on 2026-01-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0020_localinvoice_assigned_growtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='localitem',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='localitem',
            name='opening_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
