# Generated by Django 4.2.26 on 2026-02-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_inventorystock_uniq_owner_item_stock_and_more'),
        ('zoho_integration', '0021_localitem_category_localitem_current_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='localitem',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='localitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='localitem',
            name='opening_stock',
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='complaint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.complaint'),
        ),
        migrations.AlterField(
            model_name='localinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, unique=True),
        ),
    ]
