# Generated by Django 4.2.26 on 2026-02-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0022_remove_localitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
