# Generated by Django 4.2.26 on 2026-02-26 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_complaint_created_by_customer_and_more'),
        ('zoho_integration', '0023_localitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcustomer',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='localcustomer',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='localcustomer',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('shop', 'Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='localcustomer',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('shop', 'Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('shop', 'Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='localinvoiceline',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='localitem',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='localitem',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='localitem',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('shop', 'Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='localitem',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
    ]
