# Generated by Django 4.2.26 on 2025-11-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table='shop',
        ),
    ]
