# Generated by Django 4.2.26 on 2025-11-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shop_table'),
    ]

    operations = [
    ]
