# Generated by Django 4.2.26 on 2025-11-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_link_existing_shop_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table=None,
        ),
    ]
