# Generated by Django 4.2.26 on 2025-11-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shop_gst_pin_shop_owner_shop_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='approved',
            new_name='status',
        ),
    ]
