# Generated by Django 4.2.26 on 2025-11-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_approved_shop_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table='core_shop_new',
        ),
    ]
