# Generated by Django 4.2.26 on 2025-11-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_shop_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shopname',
        ),
        migrations.AlterModelTable(
            name='shop',
            table=None,
        ),
    ]
