# Generated by Django 4.2.26 on 2025-11-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_name_shop_shopname_alter_shop_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=120)),
                ('contact_person', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(db_index=True, max_length=12)),
                ('gst_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('agreement_start', models.DateField(blank=True, null=True)),
                ('agreement_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('parent_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_shops', to='core.shop')),
            ],
            options={
                'ordering': ['shopname'],
                'unique_together': {('parent_shop', 'shopname')},
            },
        ),
    ]
