# Generated by Django 4.2.26 on 2025-11-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_thirdpartyshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirdpartyshop',
            options={},
        ),
        migrations.RenameField(
            model_name='thirdpartyshop',
            old_name='contact_person',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='thirdpartyshop',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='thirdpartyshop',
            name='agreement_end',
        ),
        migrations.RemoveField(
            model_name='thirdpartyshop',
            name='agreement_start',
        ),
        migrations.RemoveField(
            model_name='thirdpartyshop',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='thirdpartyshop',
            name='parent_shop',
        ),
    ]
