# Generated by Django 4.2.26 on 2025-11-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_thirdpartyshop_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThirdPartyShop',
        ),
    ]
