# Generated by Django 4.2.26 on 2025-11-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_thirdpartyshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='adhar',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technician',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='grow_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technicians/'),
        ),
        migrations.AddField(
            model_name='technician',
            name='pincode',
            field=models.CharField(db_index=True, default='', max_length=12),
            preserve_default=False,
        ),
    ]
