# Generated by Django 4.2.26 on 2025-11-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_technician_address_technician_adhar_technician_busy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
