# Generated by Django 4.2.26 on 2025-11-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_technician_latitude_technician_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('franchise', 'Franchise'), ('other', 'Other Shop')], default='other', max_length=20),
        ),
    ]
