# Generated by Django 4.2.26 on 2025-11-14 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shop_shop_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='issue',
            new_name='address',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assign_to',
            field=models.CharField(choices=[('GrowTag', 'GrowTag'), ('ThirdParty', 'Third Party')], default='GrowTag', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='issue_details',
            field=models.TextField(default='No details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone_model',
            field=models.CharField(default='Unknown', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.shop'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.technician'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='gst_pin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
