# Generated by Django 4.2.26 on 2025-11-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_issue_complaint_address_complaint_assign_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='GrowTag/')),
                ('grow_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(db_index=True, max_length=12)),
                ('adhar', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('busy', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GrowTag', to='core.shop')),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.growtag'),
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
