# Generated by Django 4.2.26 on 2025-11-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_growtag_alter_complaint_assigned_technician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growtag',
            name='available',
        ),
        migrations.RemoveField(
            model_name='growtag',
            name='busy',
        ),
        migrations.AddField(
            model_name='growtag',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
