# Generated by Django 4.2.26 on 2025-11-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_growtag_available_remove_growtag_busy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Growtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Growtags/')),
                ('grow_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(db_index=True, max_length=12)),
                ('adhar', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Growtags', to='core.shop')),
            ],
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_technician',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assign_to',
            field=models.CharField(choices=[('Growtags', 'Growtags'), ('ThirdParty', 'Third Party')], default='Growtags', max_length=20),
        ),
        migrations.DeleteModel(
            name='GrowTag',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_Growtags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.growtags'),
        ),
    ]
