# Generated by Django 4.2.26 on 2025-11-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_growtags_remove_complaint_assigned_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='assign_to',
            field=models.CharField(choices=[('franchise', 'Franchise'), ('other', 'Other Shop'), ('growtag', 'GrowTag')], default='Growtags', max_length=20),
        ),
    ]
