# Generated by Django 4.2.26 on 2025-11-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_complaint_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='assign_to',
            field=models.CharField(choices=[('franchise', 'Franchise'), ('other shop', 'Other Shop'), ('growtag', 'GrowTag')], default='Growtags', max_length=20),
        ),
        migrations.AlterField(
            model_name='growtags',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growtags', to='core.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('franchise', 'Franchise'), ('other shop', 'Other Shop')], default='Other Shop', max_length=20),
        ),
    ]
