# Generated by Django 4.2.26 on 2025-11-19 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_complaint_assign_to_alter_growtags_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_Growtags',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_shop',
        ),
        migrations.RemoveField(
            model_name='growtags',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assign_to',
            field=models.CharField(choices=[('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'GrowTag')], default='franchise', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='customer_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Phone number must contain digits only')]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='pincode',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d+$', 'Pincode must contain digits only')]),
        ),
        migrations.AlterField(
            model_name='growtags',
            name='adhar',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Adhar must contain digits only')]),
        ),
        migrations.AlterField(
            model_name='growtags',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Phone number must contain digits only')]),
        ),
        migrations.AlterField(
            model_name='growtags',
            name='pincode',
            field=models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d+$', 'Pincode must contain digits only')]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Phone number must contain digits only')]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='pincode',
            field=models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d+$', 'Pincode must contain digits only')]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('franchise', 'Franchise'), ('othershop', 'Other Shop')], default='franchise', max_length=20),
        ),
    ]
