# Generated by Django 4.2.26 on 2025-11-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_complaint_assigned_growtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_Growtags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.shop'),
        ),
    ]
