# Generated by Django 4.2.26 on 2025-11-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_complaint_assigned_growtags_complaint_assigned_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='growtags',
            name='area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='growtags',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
