# Generated by Django 4.2.26 on 2025-11-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_growtags_area_growtags_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('growtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core.growtags')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growtag_assignments', to='core.shop')),
            ],
        ),
    ]
