# Generated by Django 4.2.26 on 2025-11-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_growtagassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
