# Generated by Django 4.2.26 on 2025-11-25 08:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_complaint_area_complaint_email_complaint_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Phone number must contain digits only')])),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('phone_model', models.CharField(blank=True, max_length=120, null=True)),
                ('issue_details', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d+$', 'Pincode must contain digits only')])),
                ('assign_to', models.CharField(blank=True, max_length=50, null=True)),
                ('assign_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.customer'),
        ),
    ]
