# Generated by Django 4.2.26 on 2025-11-29 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_complaint_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='assigned_Growtags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints_for_growtag', to='core.growtags'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='core.shop'),
        ),
    ]
