# Generated by Django 4.2.26 on 2025-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_complaint_assigned_growtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growtags',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
