# Generated by Django 4.2.26 on 2025-12-02 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_growtags_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growtags',
            name='available',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Phone number must contain digits only')]),
        ),
    ]
