# Generated by Django 4.2.26 on 2025-12-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_growtags_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
