# Generated by Django 4.2.26 on 2025-12-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_customer_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='assign_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='issue_details',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_model',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
