# Generated by Django 4.2.26 on 2025-12-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_customer_area_remove_customer_assign_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
