# Generated by Django 4.2.26 on 2025-12-22 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_complaint_created_by_complaint_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='confirm_status',
            field=models.CharField(choices=[('NOT CONFIRMED', 'Not confirmed'), ('CONFIRMED', 'Confirmed')], default='NOT CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
