# Generated by Django 4.2.26 on 2025-12-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_shop_email_alter_shop_gst_pin_alter_shop_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='core.customer')),
            ],
        ),
    ]
