# Generated by Django 4.2.26 on 2025-12-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_customerauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerauthtoken',
            name='key',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
