# Generated by Django 4.2.26 on 2025-12-31 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_customerauthtoken_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_model', models.CharField(blank=True, default='', max_length=120)),
                ('issue_detail', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('LOST', 'Lost'), ('CONVERTED', 'Converted')], default='NEW', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SALESIQ', 'SalesIQ')], default='MANUAL', max_length=20)),
                ('salesiq_visitor_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
