# Generated by Django 4.2.26 on 2026-01-03 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='core.shop')),
            ],
        ),
        migrations.CreateModel(
            name='GrowtagAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('growtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='core.growtags')),
            ],
        ),
    ]
