# Generated by Django 4.2.26 on 2026-01-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_customerpasswordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='complaint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='core.complaint'),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('COMPLAINT_REGISTERED', 'Complaint Registered')], default='NEW', max_length=30),
        ),
    ]
