# Generated by Django 4.2.26 on 2026-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_purchasebill_purchasebillpayment_purchasebillitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='payment_terms',
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20),
        ),
    ]
