# Generated by Django 4.2.26 on 2026-01-30 17:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0021_localitem_category_localitem_current_stock_and_more'),
        ('core', '0048_remove_purchasebill_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='owner_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('growtag', 'Growtag')], default='shop', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(max_length=10)),
                ('qty_change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ref_type', models.CharField(choices=[('PURCHASE_BILL', 'Purchase Bill'), ('INVOICE', 'Invoice'), ('ADJUSTMENT', 'Adjustment')], default='ADJUSTMENT', max_length=20)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('growtag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.growtags')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledgers', to='zoho_integration.localitem')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('shop', 'Shop'), ('growtag', 'Growtag')], max_length=10)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('growtag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.growtags')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stocks', to='zoho_integration.localitem')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.UniqueConstraint(fields=('owner_type', 'shop', 'growtag', 'item'), name='uniq_owner_item_stock'),
        ),
    ]
