# Generated by Django 4.2.26 on 2026-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_purchasebill_growtag_purchasebill_owner_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorystock',
            name='uniq_owner_item_stock',
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='owner_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('growtag', 'Growtag')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['owner_type', 'shop', 'growtag', 'item'], name='core_stockl_owner_t_d5a555_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['ref_type', 'ref_id'], name='core_stockl_ref_typ_e51a67_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'shop')), fields=('shop', 'item'), name='uniq_shop_item_stock'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'growtag')), fields=('growtag', 'item'), name='uniq_growtag_item_stock'),
        ),
    ]
