# Generated by Django 4.2.26 on 2026-02-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_customerpasswordresettoken_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.shop'),
        ),
    ]
