# Generated by Django 4.2.26 on 2026-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_vendor_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('COMPLAINT_REGISTERED', 'Complaint Registered'), ('CONVERTED', 'Converted')], default='NEW', max_length=30),
        ),
    ]
