# Generated by Django 4.2.26 on 2026-02-12 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.shop'),
        ),
    ]
