# Generated by Django 4.2.26 on 2026-02-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_purchaseorder_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='ref_type',
            field=models.CharField(choices=[('PURCHASE_BILL', 'Purchase Bill'), ('INVOICE', 'Invoice'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], default='ADJUSTMENT', max_length=20),
        ),
    ]
