# Generated by Django 4.2.26 on 2026-02-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_customerpasswordotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='customerpasswordresettoken',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='customerpasswordresettoken',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='customerpasswordresettoken',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='growtagassignment',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='growtagassignment',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='growtagassignment',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='growtags',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='growtags',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='growtags',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchasebillpayment',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchasebillpayment',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchasebillpayment',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_shop', to='core.shop'),
        ),
    ]
