# Generated by Django 4.2.26 on 2026-02-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_complaint_created_by_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='growtag',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='owner_type',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='shop',
        ),
    ]
