# Generated by Django 4.2.26 on 2026-02-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_purchasebill_growtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='owner_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('growtag', 'Growtag')], default='shop', max_length=10),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.shop'),
        ),
    ]
