# Generated by Django 4.2.26 on 2026-02-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0023_localitem_is_active'),
        ('core', '0060_purchasebill_growtag_purchasebill_owner_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='zoho_integration.localitem'),
        ),
    ]
