# Generated by Django 4.2.26 on 2026-02-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_purchaseorderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_created', to='core.customer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_created', to='core.shop'),
        ),
    ]
