# Generated by Django 4.2.26 on 2026-02-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_complaint_created_by_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='created_by_customer',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='created_by_shop',
        ),
    ]
