# Generated by Django 4.2.26 on 2026-02-27 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_complaint_created_by_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
