# Generated by Django 4.2.26 on 2026-02-28 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0064_lead_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='customerpasswordresettoken',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='customerpasswordresettoken',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='customerpasswordresettoken',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerpasswordresettoken',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='growtagassignment',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='growtagassignment',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='growtagassignment',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='growtagassignment',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='growtags',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='growtags',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='growtags',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='growtags',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchasebillpayment',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchasebillpayment',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchasebillpayment',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillpayment',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_growtag', to='core.growtags'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('franchise', 'Franchise'), ('othershop', 'Other Shop'), ('growtag', 'Growtag'), ('customer', 'Customer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_shop', to='core.shop'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerpasswordresettoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='growtagassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='growtags',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasebillitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasebillpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
