# Generated by Django 4.2.26 on 2026-03-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_complaint_created_by_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, default='IN', max_length=2)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, default='', max_length=120)),
                ('area', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'unique_together': {('country', 'code')},
            },
        ),
    ]
