# Generated by Django 4.2.26 on 2026-03-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_postalcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalcode',
            name='area',
        ),
    ]
