# Generated by Django 4.2.26 on 2026-03-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_postalcode_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.growtags'),
        ),
    ]
