# Generated by Django 4.2.26 on 2026-03-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_purchaseorder_growtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='owner_type',
        ),
    ]
