# Generated by Django 4.2.26 on 2025-12-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
    ]
