# Generated by Django 4.2.26 on 2026-02-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_stockledger_ref_type'),
        ('expenses', '0002_remove_expense_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='owner_growtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.growtags'),
        ),
        migrations.AddField(
            model_name='expense',
            name='owner_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
        migrations.AddField(
            model_name='expense',
            name='owner_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('growtag', 'Growtag'), ('admin', 'Admin')], default='shop', max_length=10),
        ),
    ]
