# Generated by Django 4.2.26 on 2026-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_owner_growtag_expense_owner_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='owner_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('growtag', 'Growtag'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
